/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ead_cw;

import javax.swing.JOptionPane;

/**
 *
 * @author kavis
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setLocationRelativeTo(null);
        configureAccess();
    }

    private void configureAccess() {
        String role = UserSession.getRole();
        String username = UserSession.getUsername();

        setTitle("PetCare - "
                + (username == null ? "No active user" : username)
                + (role == null ? "" : " (" + role + ")"));

        boolean admin = "ADMIN".equals(role);
        boolean receptionist = "RECEPTIONIST".equals(role);
        boolean veterinarian = "VETERINARIAN".equals(role);

        btnCustomers.setVisible(admin || receptionist);
        btnPets.setVisible(admin || receptionist);
        btnAppointment.setVisible(admin || receptionist);
        btnPayments.setVisible(admin || receptionist);

        btnTreatments.setVisible(admin || veterinarian);

        btnPriceSchedule.setVisible(admin);
        btnVeterinarians.setVisible(admin);
        btnReports.setVisible(admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnPets = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnTreatments = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnPriceSchedule = new javax.swing.JButton();
        btnVeterinarians = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PetCare Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLogout.setBackground(new java.awt.Color(255, 73, 73));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnCustomers.setBackground(new java.awt.Color(188, 204, 255));
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(this::btnCustomersActionPerformed);

        btnPets.setBackground(new java.awt.Color(188, 204, 255));
        btnPets.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPets.setText("Pets");
        btnPets.addActionListener(this::btnPetsActionPerformed);

        btnAppointment.setBackground(new java.awt.Color(188, 204, 255));
        btnAppointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAppointment.setText("Appointments");
        btnAppointment.addActionListener(this::btnAppointmentActionPerformed);

        btnTreatments.setBackground(new java.awt.Color(188, 204, 255));
        btnTreatments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTreatments.setText("Treatments");
        btnTreatments.addActionListener(this::btnTreatmentsActionPerformed);

        btnPayments.setBackground(new java.awt.Color(188, 204, 255));
        btnPayments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPayments.setText("Payments");
        btnPayments.addActionListener(this::btnPaymentsActionPerformed);

        btnReports.setBackground(new java.awt.Color(188, 204, 255));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReports.setText("Report");
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnPriceSchedule.setBackground(new java.awt.Color(188, 204, 255));
        btnPriceSchedule.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPriceSchedule.setText("Price Schedule");
        btnPriceSchedule.addActionListener(this::btnPriceScheduleActionPerformed);

        btnVeterinarians.setBackground(new java.awt.Color(188, 204, 255));
        btnVeterinarians.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVeterinarians.setText("Veterinarians");
        btnVeterinarians.addActionListener(this::btnVeterinariansActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnLogout)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVeterinarians, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPriceSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnPriceSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVeterinarians, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int answer = JOptionPane.showConfirmDialog(
                this,
                "Do you want to logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION);

        if (answer == JOptionPane.YES_OPTION) {
            UserSession.logout();
            LoginForm login = new LoginForm();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        Customer customerForm = new Customer();
        customerForm.setLocationRelativeTo(null);
        customerForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
        PetForm petForm = new PetForm();
        petForm.setLocationRelativeTo(null);
        petForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPetsActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        AppointmentForm appointmentForm = new AppointmentForm();
        appointmentForm.setLocationRelativeTo(null);
        appointmentForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void btnTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentsActionPerformed
        TreatmentForm treatmentForm = new TreatmentForm();
        treatmentForm.setLocationRelativeTo(null);
        treatmentForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTreatmentsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        PaymentForm paymentForm = new PaymentForm();
        paymentForm.setLocationRelativeTo(null);
        paymentForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        ReportForm reportForm = new ReportForm();
        reportForm.setLocationRelativeTo(null);
        reportForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnPriceScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceScheduleActionPerformed
        PriceScheduleForm priceScheduleForm = new PriceScheduleForm();
        priceScheduleForm.setLocationRelativeTo(null);
        priceScheduleForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPriceScheduleActionPerformed

    private void btnVeterinariansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeterinariansActionPerformed
        VeterinarianForm veterinarianForm = new VeterinarianForm();
        veterinarianForm.setLocationRelativeTo(null);
        veterinarianForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVeterinariansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnPets;
    private javax.swing.JButton btnPriceSchedule;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnTreatments;
    private javax.swing.JButton btnVeterinarians;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
